spring:
  application:
    name: d14

  profiles:
    active: local

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false

server:
  port: 8080

logging:
  level:
    root: INFO
    com.yapp.d14: DEBUG
